# -*- coding: utf-8 -*-
"""
Created on Sat Dec 24 15:27:05 2022

@author: marcos
"""


def club_urls():
    return {
        "inglaterra": [
            "arsenal",
            "aston-villa-fc",
            "chelsea-fc",
            "everton-fc",
            "liverpool",
            "manchester-city-fc",
            "manchester-united-fc",
            "newcastle-united-fc",
            "tottenham-hotspur-fc",
            "west-ham-united",
            "wolverhampton",
            "birmingham-city-fc",
            "blackburn-rovers-fc",
            "blackpool-fc",
            "bolton-wanderers-fc",
            "burnley-fc",
            "afc-bournemouth",
            "brighton-amp-hov",
            "brentford",
            "cardiff-city-fc",
            "charlton-athletic-fc",
            "crystal-palace-fc",
            "derby-county-fc",
            "fulham",
            "huddersfield-town-fc",
            "hull-city",
            "ipswich-town-fc",
            "leeds-united-afc",
            "leicester-city-fc",
            "middlesbrough-fc",
            "millwall-fc",
            "norwich-city-fc",
            "nottingham-forest-fc",
            "plymouth-argyle",
            "portsmouth",
            "preston-north-end",
            "queens-park-rangers-fc",
            "reading-fc",
            "rotherham-united",
            "sheffield-united",
            "southampton-fc",
            "stoke-city",
            "sunderland-afc",
            "swansea-city-afc",
            "watford-fc",
            "west-bromwich",
            "wigan-athletic",
        ],
        ########
        # ITALIA
        "italia": [
            "atalanta",
            "bologna",
            "cagliari",
            "empoli-fc",
            "fiorentina",
            "hellas-verona-fc",
            "internazionale",
            "juventus-fc",
            "lazio",
            "milan",
            "napoli",
            "palermo",
            "parma-fc",
            "roma",
            "sampdoria",
            "us-sassuolo-calcio",
            "torino-fc",
            "udinese",
            "as-bari",
            "brescia",
            "chievo",
            "us-cremonese",
            "frosinone-calcio",
            "genoa",
            "lecce",
            "ac-monza-brianza-1912",
            "perugia",
            "pisa-calcio",
            "reggina",
            "salernitana-calcio-1919",
            "spal-1907",
            "asd-spezia",
            "venezia",
        ],
        ########
        # ESPANHA
        "espanha": [
            "athletic-bilbao",
            "atletico-madrid",
            "barcelona",
            "betis",
            "celta",
            "espanyol",
            "mallorca",
            "osasuna",
            "real-madrid",
            "real-sociedad",
            "sevilla",
            "valencia-cf",
            "villarreal",
            "alaves",
            "almeria",
            "cadiz",
            "deportivo",
            "elche",
            "getafe",
            "girona-fc",
            "granada",
            "huesca",
            "levante",
            "malaga",
            "rm-castilla",
            "tenerife",
            "ud-palmas",
            "racing",
            "rayo-vallecano",
            "real-zaragoza",
            "sporting-gijon",
            "valladolid",
        ],
        ########
        # ALEMANHA
        "alemanha": [
            "fc-augsburg",
            "bayer-leverkusen",
            "borussia-dortmund",
            "borussia-monchengla",
            "bayern-munchen",
            "1-fc-koln",
            "eintracht-frankfurt",
            "hamburger-sv",
            "hertha-bsc",
            "tsg-1899-hoffenheim",
            "mainz-amat",
            "rb-leipzig",
            "schalke-04",
            "sc-freiburg",
            "1-fc-union-berlin",
            "stuttgart",
            "werder-bremen",
            "wolfsburg",
            "1860-munchen",
            "arminia-bielefeld",
            "bochum",
            "darmstadt-98",
            "eintracht-brau-hellip",
            "hansa-rostock",
            "karlsruher-sc",
            "fc-nurnberg",
            "fortuna-dusseldorf",
            "hannover-96",
            "kaiserslautern",
            "paderborn",
            "saarbrucken",
            "sg-dynamo-dresden",
            "st-pauli",
        ],
        ########
        # FRANÇA
        "franca": [
            "angers-sco",
            "ajaccio",
            "auxerre",
            "bastia",
            "bordeaux",
            "caen",
            "clermont-foot",
            "dijon-fco",
            "guingamp",
            "havre-ac",
            "lens",
            "lillestrom",
            "lorient",
            "metz",
            "monaco",
            "montpellier-hsc",
            "nancy",
            "nantes",
            "nice",
            "nimes-olympique",
            "olympique-lyonnais",
            "olympique-marsella",
            "paris-sg",
            "paris-saint-germain-fc",
            "saint-etienne",
            "stade-brestois-29",
            "stade-reims",
            "stade-rennes",
            "strasbourg",
            "toulouse-fc",
            "sochaux",
        ],
        ########
        # PORTUGAL
        "portugal": [
            "benfica",
            "fc-porto",
            "sporting-lisbon",
            "sporting-braga",
            "vitoria-guimaraes",
            "academica",
            "academico-viseu",
            "arouca",
            "belenenses",
            "chaves",
            "boavista",
            "estoril",
            "famalicao",
            "gil-vicente",
            "maritimo",
            "nacional",
            "pacos-ferreira",
            "penafiel",
            "portimonense",
            "rio-ave",
            "santa-clara",
        ],
        #############################
        "europa": [
            # HOLANDA
            "ajax",
            "psv",
            "feyenoord",
            "fc-twente-1965",
            "az",
            "fc-groningen",
            "heerenveen",
            "sparta-rotterdam",
            "fc-utrecht",
            "vitesse",
            # BELGICA
            "anderlecht",
            "antwerp",
            "club-brugge",
            "genk",
            "kaa-gent",
            "standard-liege",
            "union-saint-gilloise",
            # ESCOCIA
            "celtic-fc",
            "glasgow-rangers-fc",
            "aberdeen",
            "heart-of-midlo",
            "hibernian-fc",
            # IRLANDA
            "dundalk",
            "shamrock-rovers",
            ##################
            # NORDICOS
            ##################
            # DINAMARCA
            "aalborg-bk",
            "brondby-if",
            "fc-kobenhavn",
            "midtjylland",
            "odense-bk",
            "nordsj-aelig-lland",
            "randers",
            # SUECIA
            "malmo-ff",
            "if-elfsborg-boras",
            "ifk-goteborg",
            "aik-solna",
            "djurgardens-if",
            "ifk-norrkoping",
            # NORUEGA
            "rosenborg-bk",
            "molde-fk",
            "fk-bodo-glimt",
            "lillestrom-sk",
            "sk-brann-bergen",
            "viking-stavanger",
            # FINLANDIA
            "hjk-helsinki",
            "kups-kuopio",
            # BALTICOS
            "caramba-dinamo-riga",
            "rigas-futbola-skola",
            "zalgiris-vilnius",
            "flora",
            ##################
            # TURQUIA
            "fenerbahce",
            "galatasaray-sk",
            "be-ikta",
            "bursaspor",
            "antalyaspor",
            "eskisehirspor",
            "istanbul-bb",
            "sivasspor",
            "trabzonspor",
            # GRECIA
            "olympiakos-piraeus",
            "aek-athens",
            "panathinaikos",
            "paok",
            "aris",
            # CHIPRE
            "apoel",
            "aek-larnaca",
            "apollon",
            "omonia-nicosia",
            "anorthosis",
            # ISRAEL
            "maccabi-tel-aviv",
            "maccabi-haifa-fc",
            "hapoel-be-er-sheva",
            "hapoel-tel-aviv",
            ######################
            # EUROPA CENTRAL
            ######################
            # SUIÇA
            "basel",
            "grasshopper",
            "zurich",
            "bsc-young-boys-bern",
            "fc-vaduz",
            # AUSTRIA
            "salzburgo",
            "lask-linz",
            "rapid-wien",
            "sturm-graz",
            "austria-wien",
            # POLONIA
            "kp-legia-warszawa",
            "lech-pozna",
            "wisla-krakow-ssa",
            "ks-gornik-zabrze",
            # TCHECOSLOVAQUIA
            "sk-sigma-olomouc",
            "slavia-praha",
            "sparta-praha",
            "slovan-liberec",
            "viktoria-plze",
            "slovan-bratislava",
            "ilina",
            "maribor",
            "olimpija-ljubljana",
            # BULGARIA
            "cska-sofia",
            "levski-sofia",
            "ludogorets",
            # HUNGRIA
            "budapesti-vasas-sc",
            "debreceni-vsc",
            "ferencvaros-budapest",
            "budapest-honved-fc",
            "ujpest-fc",
            # ROMENIA
            "steaua-bucure-ti",
            "cfr-cluj",
            "fc-rapid-bucuresti",
            # SERVIA
            "crvena-zvezda",
            "fk-partizan-beograd",
            # CROACIA
            "dinamo-zagreb",
            "hajduk-split",
            # BALCAS
            "tirana",
            "vardar",
            "kf-ballkani",
            "kf-drita",
            # BOSNIA
            "sarajevo",
            "zeljeznicar",
            "zrinjski",
            ######################
            # URSS
            ######################
            # ASIA CENTRAL
            "qaraba-a-dam-fk",
            "fk-neftchi",
            "pyunik",
            "dinamo-tbilisi",
            "astana",
            "aktobe",
            "kairat-almaty",
            "tobol-kostanay",
            # UCRANIA
            "fc-shakhtar-donetsk",
            "dinamo-kiev",
            "sk-dnipro-1",
            # BELARUS
            "bate-borisov",
            "dinamo-minsk",
            # MOLDAVIA
            "sheriff",
            # RUSSIA
            "dinamo-moskva",
            "cska-moskva",
            "fk-krasnodar",
            "fk-rostov-na-donu",
            "lokomotiv-moskva",
            "rubin-kazan",
            "spartak-moskva",
            "pfc-sochi",
            "zenit-st-petersburg",
            ######################
            # PEQUENOS
            ######################
            "lincoln-red-imps-fc",
        ],
        #############################
        # @@@@@@@@@@@@@@@@@@@@@@@@@@@
        #############################
        "brasil": [
            "atletico-mineiro",
            "corinthians-sao-paulo",
            "coritiba-fbc",
            "cruzeiro-belo-horizonte",
            "flamengo-rio-janeiro",
            "fluminense-rio-janeiro",
            "gremio-porto-alegre",
            "goias-goiania",
            "internacional",
            "palmeiras",
            "a-portuguesa-d",
            "santos-fc",
            "sao-paulo-fc",
            "vasco-da-gama",
            "abc",
            "altos",
            "america-mineiro",
            "america-rj",
            "america-rnfc",
            "avai",
            "atletico-go",
            "ec-bahia",
            "bangu",
            "botafogo-pb",
            "botafogo-sp",
            "bragantino",
            "brasiliense-fc",
            "brasil-de-pelotas",
            "campinense",
            "cascavel-fc",
            "caxias",
            "ceara",
            "chapecoense",
            "confianca",
            "crb",
            "criciuma-ec",
            "cuiaba",
            "csa",
            "ferroviaria",
            "figueirense-florianopolis",
            "fortaleza-ec",
            "gama-br",
            "guarani-campinas",
            "inter-de-limeira",
            "ituano",
            "joinville",
            "juventude-caxias-do-sul",
            "londrina",
            "madureira-rj",
            "manaus",
            "mirassol",
            "mogi-mirim",
            "nacional-am",
            "nautico-recife",
            "nova-iguacu",
            "novorizontino",
            "oeste",
            "operario-pr",
            "parana-clube",
            "paysandu-belem",
            "ponte-preta",
            "portuguesa-rj",
            "remo",
            "resende",
            "sampaio-correa-fc",
            "santa-cruz-recife",
            "sao-bento",
            "sao-bernardo-fc",
            "sao-caetano",
            "santo-andre",
            "sergipe",
            "sport-recife",
            "tombense",
            "vila-nova",
            "vitoria",
            "volta-redonda",
            "xv-piracicaba",
        ],
        #############################
        "argentina": [
            "argentinos-juniors",
            "arsenal-sarandi-fc",
            "ca-banfield",
            "barracas-central",
            "belgrano",
            "ca-boca-juniors",
            "colon-santa-fe",
            "defensa-justicia",
            "estudiantes-plata",
            "ferro-carril-oeste",
            "gimnasia-plata",
            "godoy-cruz-antonio-tomba",
            "ca-huracan",
            "independiente",
            "instituto",
            "ca-lanus",
            "newells-old-boys",
            "quilmes",
            "platense",
            "racing-club-avellaneda",
            "ca-river-plate",
            "ca-rosario-central",
            "sarmiento",
            "talleres-cordoba",
            "ca-tigre",
            "union-santa-fe",
            "ca-velez-sarsfield",
        ],
        #############################
        # AMERICA DO SUL
        #############################
        "america_sul": [
            "nacional-montevideo",
            "penarol-montevideo",
            "danubio-montevideo",
            "defensor-sporting",
            "liverpool-montevideo",
            "montevideo-wanderers",
            "plaza-colonia",
            "cerro-porteno",
            "guarani",
            "libertad-asuncion",
            "olimpia-asuncion",
            "nacional-asuncion",
            "rubio-nu",
            "sportivo-luqueno",
            "sol-america",
            "audax-italiano",
            "cobreloa",
            "cobresal",
            "colo-colo",
            "everton",
            "universidad-chile",
            "univ-catolica",
            "huachipato",
            "nublense",
            "palestino",
            "santiago-wanderers",
            "union-espanola",
            "union-calera",
            "univ-concepcion",
            "always-ready",
            "blooming",
            "bolivar",
            "club-aurora",
            "club-universitario",
            "the-strongest",
            "guabira-santa-cruz",
            "jorge-wilstermann-40",
            "nacional-potosi",
            "oriente-petrolero",
            "san-jose-oruro",
            "real-santa-cruz",
            "real-potosi",
            "royal-pari-fc",
            "alianza-lima",
            "deportivo-muni",
            "carlos-manucci-trujillo",
            "fbc-melgar-arequipa",
            "sporting-cristal-lima",
            "club-cienciano",
            "real-atletico",
            "sport-boys-callao",
            "sport-huancayo",
            "universitario-lima",
            "universidad-ce-hellip",
            "utc-cajamarca",
            "barcelona-guayaquil",
            "deportivo-cuenca",
            "deportivo-quito",
            "emelec-guayaquil",
            "cd-el-nacional",
            "liga-quito",
            "csd-independiente-valle",
            "universidad-catolica-ecuador",
            "america-cali",
            "atletico-nacional",
            "deportivo-cali",
            "equidad",
            "independiente-medellin",
            "junior",
            "millonarios-bogota",
            "santa-fe",
            "deportes-tolima",
            "caracas-venezuela",
            "deportivo-tachira-fc",
            "estudiantes-merida-fc",
            "deportivo-la-guaira",
            "zamora-cf",
        ],
        #############################
        # @@@@@@@@@@@@@@@@@@@@@@@@@@@
        #############################
        "concacaf": [
            # MEXICO
            "america",
            "atlante",
            "fc-atlas-guadalajara",
            "cdsc-cruz-azul",
            "guadalajara",
            "fc-juarez",
            "leon-club",
            "mazatlan-fc",
            "monterrey",
            "necaxa",
            "pachuca",
            "puebla-fc",
            "queretaro",
            "santos-laguna",
            "san-luis",
            "tijuana",
            "tigres-uanl",
            "toluca",
            # EUA
            "atlanta-united-fc",
            "austin-fc",
            "charlotte-mls",
            "chicago-fire",
            "colorado-rapids",
            "columbus-crew",
            "dc-united",
            "fc-cincinnati",
            "fc-dallas",
            "kansas-city-wizards",
            "inter-miami-cf",
            "houston-dynamo",
            "los-angeles-football-club",
            "angeles-galaxy",
            "minnesota-united",
            "montreal-impact",
            "nashville-sc",
            "new-york-city",
            "new-england-revolution",
            "ny-cosmos",
            "orlando-city-us",
            "philadelphia-union",
            "portland-timbers",
            "real-salt-lake",
            "red-bull-new-york",
            "san-jose-earthquakes-usa",
            "seattle-sounders-fc",
            # 'saint-louis-city',
            "toronto-fc",
            "whitecaps",
            #############################
            # america central
            # COSTA RICA
            "deportivo-saprissa",
            "alajuelense",
            "herediano",
            # HONDURAS
            "cd-olimpia",
            "cd-motagua",
            "real-espana",
            # EL SALVADOR
            "alianza",
            "aguila",
            # NICARAGUA
            "real-esteli",
        ],
        #############################
        # @@@@@@@@@@@@@@@@@@@@@@@@@@@
        #############################
        "asia": [
            # ARABIA
            "al-ahli-jeddah",
            "al-ittifaq-dammam",
            "al-hilal",
            "al-ittihad",
            "al-nassr",
            "al-shabab",
            "al-taawon",
            # BAHREIN
            "muharraq",
            "manama",
            "al-rifaa",
            # QATAR
            "al-arabi-312",
            "al-gharafa",
            "al-sadd",
            "qatar-sc",
            "al-duhail-sc",
            "al-rayyan",
            # UAE
            "al-ain-62",
            "al-jazira",
            "al-sharjah",
            "al-wehda",
            "al-wasl",
            "shabab-al-ahli-dubai",
            # IRA
            "persepolis",
            "esteghlal",
            "sepahan",
            "tractor-sazi",
            "zob-ahan",
            # IRAQUE
            "al-quwa-al-jawiya",
            "al-zawraa",
            "al-talaba",
            # KUWAIT
            "al-kuwait-kw",
            "al-arabi",
            # LIBANO
            "al-ahed-lb",
            "al-ansar-lb",
            "al-nejmeh-lb",
            # UZBEQUISTAO
            "bunyodkor",
            "pakhtakor",
            #############################
            # ASIA
            #############################
            # JAPAO
            "albirex-niigata",
            "cerezo-osaka",
            "consadole-sapporo",
            "fc-tokyo",
            "gamba-osaka",
            "kashima-antlers",
            "kashiwa-reysol",
            "kawasaki-frontale",
            "kyoto-sanga",
            "nagoya-grampus",
            "sagan-tosu",
            "sanfrecce-hiroshima",
            "shonan-bellmare",
            "tokyo-verdy",
            "urawa-reds",
            "vissel-kobe",
            "yokohama",
            "yokohama-fc",
            # COREIA
            "busan-i-park",
            "daegu-fc",
            "fc-seoul",
            "gangwon-fc",
            "jeonbuk-motors",
            "jeju-united",
            "incheon-united",
            "pohang-steelers",
            "ulsan-horang-i",
            "sangju-sangmu",
            "suwon-bluewings",
            "seongnam",
            # CHINA
            "beijing-guoan",
            "dalian-aerbin",
            "hebei-zhongji",
            "jiangsu-sainty",
            "guangzhou-ever",
            "shandong-luneng",
            "shanghai-shenhua",
            "shanghai-sipg",
            # INDIA
            "fc-goa",
            "chennaiyin-fc",
            "delhi-dynamos-fc",
            "east-bengal-club",
            "hyderabad-fc",
            "kerala-blasters-fc",
            "mohun-bagan-ac",
            "mumbai-city-fc",
            # INDONESIA
            "persebaya",
            "persib",
            "persisam-putra-samarinda",
            "psm-makassar",
            # SUDESTE ASIATICO
            "buriram-united",
            "johor-fc",
            "ha-noi-t",
            "phnom-penh-crown",
            # AUSTRALIA
            "melbourne-city",
            "sydney-fc",
            "adelaide-united",
            "brisbane-roar",
            "central-coast-mariners",
            "melbourne-victory",
            "newcastle-jets",
            "perth-glory",
            "western-sydney-wanderers-fc",
            "wellington-phoenix",
            "auckland-city-fc",
        ],
        #############################
        # @@@@@@@@@@@@@@@@@@@@@@@@@@@
        #############################
        "africa": [
            # EGITO
            "al-ahly",
            "zamalek-sc",
            # MARROCOS
            "raja-casablanca",
            "wydad-casablanca",
            # TUNISIA
            "club-africain",
            "esperance-tunis",
            "etoile-sahel",
            "cs-sfaxien",
            # ARGELIA
            "es-setif",
            "belouizdad",
            "kabylie",
            "mc-alger",
            "usm-alger",
            # LIBIA
            "al-ahly-benghazi",
            # SUDAO
            "al-hilal-omdurman",
            "al-merreikh-sd",
            "Asec",
            "mamelodi-sundowns",
            "orlando-pirates",
            "kaizer-chiefs",
            "primeiro-de-agosto",
            "petroleos-luanda",
            "simba-sc",
            "hearts-of-oak",
            "enyimba",
            "tp-mazembe",
            "v-club",
            "cotonsport",
            "horoya-ac",
            "kedus-giorgis",
            "vipers-sc",
            "fc-platinum",
        ],
    }
